name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Download
        run:  Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Extract
        run:  Expand-Archive ngrok.zip
      - name: Auth
        run:  .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable TS
        run:  |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: UserSetting
        run:  | 
          tzutil.exe /s "Tokyo Standard Time"
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -name "HideFileExt" -Value 0
          Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -name "Hidden" -Value 1
          Set-WinHomeLocation 122
          Set-WinSystemLocale -SystemLocale ja-JP	
          Set-WinUILanguageOverride -Language ja-JP
      
      - name: Experience
        run: |
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoAdminLogon' -Value '1'
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'DefaultUserName' -Value 'runneradmin'
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'DefaultPassword' -Value 'P@ssw0rd!'
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoLogonCount' -Value '1'
        # echo 'ngrok tcp --region jp 3389' | Out-File -FilePath $env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\ngrok_startup.bat -Encoding ASCII
        # Set-RDWebClientAccess -ClientAuthenticationMethod Basic -AllowWebContentCaching $true
        # Install-WindowsFeature Remote-Desktop-Services,RDS-Web-Access,RDS-RD-Server,RDS-Connection-Broker,RDS-Licensing -IncludeManagementTools
        # Install-Module -Name RDWebClientManagement -Force
        # Install-RDWebClientPackage
      - name: Create Tunnel
        run:  |
          Start-Process -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp","--region","jp","3389"
          ping 127.0.0.1 /t
