name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Download
        run:  Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Extract
        run:  Expand-Archive ngrok.zip
      - name: Auth
        run:  .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable TS
        run:  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
      - run:  Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run:  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - run:  Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: UserSetting
        run:  tzutil.exe /s "Tokyo Standard Time"
      - run:  Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -name "HideFileExt" -Value 0
      - run:  Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -name "Hidden" -Value 1
      - run:  Set-WinHomeLocation 122
      - run:  Set-WinSystemLocale -SystemLocale ja-JP	
      - run:  Set-WinUILanguageOverride -Language ja-JP
        
      - name: Create Tun
        run:  .\ngrok\ngrok.exe tcp 3389
